### ISSUE TITLE
Error on startup "No module named 'prompt_toolkit.key_binding.input_processor"

### ISSUE THREAD

**Issue by Hultner** [prompt-toolkit/ptpython#276]
I get the following error when starting ptpython

```sh
$ ptpython
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ptpython/repl.py", line 271, in run_config
    six.exec_(code, namespace, namespace)
  File "/Users/hultner/.ptpython/config.py", line 8, in <module>
    from prompt_toolkit.key_binding.input_processor import KeyPress
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.input_processor'
```

Running python 3.7, following details:
```sh
 » pip --version
pip 18.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

 » python3 --version
Python 3.7.1


 » pip list
Package           Version
----------------- ---------
…
docopt            0.6.2
ipython           7.1.1
ipython-genutils  0.2.0
jedi              0.13.1
parso             0.3.1
…
prompt-toolkit    2.0.7
ptpython          2.0.4
Pygments          2.2.0
…
six               1.11.0
wcwidth           0.1.7
…
```

After this message ptpython actually boots so the Exception doesn't seem fatal to the program.

Looking into the prompt_toolkit API I can find the following which looks relevant [prompt_toolkit.key_binding.**key_processor**.KeyPress](https://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html#prompt_toolkit.key_binding.key_processor.KeyPress) alongside with a reference from the changelog for version 2.0.1, saying [`input_processor` was renamed to `key_processor`.](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/CHANGELOG#L229).

From this I could find dig through some changes and find the following https://github.com/prompt-toolkit/ptpython/commit/fe15a6504f5cbcdabf535d24e96be4aee22e4152#diff-121a2a1efa4902e59db6b46ed6ad4543L8 which tells me this was changed in the example config. But for me who upgrade from an older version of ptpython results in an error (I haven't really changed the base config either). 

My suggestion would be to either fix this automatically when starting a new version with an old config or catch this error and print some guidance on how to fix it. If not that at least document it clearly here on the repo so it can be easily found by a search (googling the error yielded no relevant result for me).

**Comment by shaypal5** [comment]
Same here.
