### ISSUE TITLE
in windows platform,if installed ptpython ,ipython not usable

### ISSUE THREAD

**Issue by ljm9104** [prompt-toolkit/ptpython#291]
λ ipython
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\ipython.exe\__main__.py", line 5, in <module>
  File "c:\python36\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "c:\python36\lib\site-packages\IPython\terminal\embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "c:\python36\lib\site-packages\IPython\terminal\interactiveshell.py", line 22, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application'

**Comment by jonathanslenders** [comment]
Hi @ljm9104,

Can you tell me which IPython version you are using? Normally, the latest version should be compatible.

**Comment by ljm9104** [comment]
I use the Ipython 6.5.0 on windows platform
