### ISSUE TITLE
ptipython ImportError: No module named IPython.terminal.embed

### ISSUE THREAD

**Issue by arthurzenika** [prompt-toolkit/ptpython#3]
```
$ ptipython 
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/ptpython/bin/ptipython", line 9, in <module>
    load_entry_point('prompt-toolkit==0.21', 'console_scripts', 'ptipython')()
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/prompt_toolkit/contrib/entry_points/ptipython.py", line 22, in <module>
    from prompt_toolkit.contrib.ipython import embed
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/prompt_toolkit/contrib/ipython.py", line 18, in <module>
    from IPython.terminal.embed import InteractiveShellEmbed as _InteractiveShellEmbed
ImportError: No module named IPython.terminal.embed
```

**Comment by mknecht** [comment]
For completeness sake, this happens also if you have an outdated version of IPython installed. In that case, upgrade. E.g. I upgraded from IPython 0.13.2 to 4.0.0

**Comment by gioulisapo** [comment]
In my case I had to run `sudo pip2 install ipython`. If the default version of python is 3.x.x then the warning banned added by @jonathanslenders does not appear.
