### ISSUE TITLE
Crashes after Runtime error 

### ISSUE THREAD

**Issue by ECon87** [prompt-toolkit/ptpython#457]
Great idea. I love the idea of history and vim bindings, but for the life of me it cannot stay on for more than 10 mins. It keeps on crashing after a runtime error.

The exception is:

```
an error occurred during closing of asynchronous generator <async_generator object generator_to_async_generator at 0x7f62f5fdbca0>
asyncgen: <async_generator object generator_to_async_generator at 0x7f62f5fdbca0>
RuntimeError: aclose(): asynchronous generator is already running
an error occurred during closing of asynchronous generator <async_generator object ThreadedCompleter.get_completions_async at 0x7f62f5d525e0>
asyncgen: <async_generator object ThreadedCompleter.get_completions_async at 0x7f62f5d525e0>
RuntimeError: aclose(): asynchronous generator is already running
Traceback (most recent call last):
  File "/home/username/.local/bin/ptpython", line 8, in <module>
    sys.exit(run())
  File "/home/username/.local/lib/python3.9/site-packages/ptpython/entry_points/run_ptpython.py", line 205, in run
    embed(
  File "/home/username/.local/lib/python3.9/site-packages/ptpython/repl.py", line 692, in embed
    repl.run()
  File "/home/username/.local/lib/python3.9/site-packages/ptpython/repl.py", line 107, in run
    text = self.read()
  File "/home/username/.local/lib/python3.9/site-packages/ptpython/python_input.py", line 1027, in read
    result = self.app.run(pre_run=pre_run, in_thread=True)
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 870, in run
    raise exception
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 851, in run_in_thread
    result = self.run(
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 887, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 798, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 945, in cancel_and_wait_for_background_tasks
    await task
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/buffer.py", line 1738, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 227, in get_completions_async
    async for completion in generator_to_async_generator(
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/eventloop/async_generator.py", line 74, in generator_to_async_generator
    await runner_f
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/eventloop/async_generator.py", line 43, in runner
    for item in get_iterable():
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 228, in <lambda>
    lambda: self.completer.get_completions(document, complete_event)
  File "/home/username/.local/lib/python3.9/site-packages/ptpython/completer.py", line 601, in get_completions
    completions = list(self.completer.get_completions(document, complete_event))
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/completion/deduplicate.py", line 28, in get_completions
    for completion in self.completer.get_completions(document, complete_event):
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 329, in get_completions
    for c in completer.get_completions(document, complete_event):
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 301, in get_completions
    for c in self.completer.get_completions(document, complete_event):
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/completion/fuzzy_completer.py", line 91, in _get_fuzzy_completions
    completions = list(self.completer.get_completions(document2, complete_event))
  File "/home/username/.local/lib/python3.9/site-packages/ptpython/completer.py", line 193, in get_completions
    yield from self._jedi_completer.get_completions(
  File "/home/username/.local/lib/python3.9/site-packages/ptpython/completer.py", line 260, in get_completions
    jedi_completions = sorted(
  File "/home/username/.local/lib/python3.9/site-packages/ptpython/completer.py", line 264, in <lambda>
    jc.type != "param",
  File "/home/username/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 719, in type
    return super().type
  File "/home/username/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 189, in type
    return self._name.api_type
  File "/home/username/.local/lib/python3.9/site-packages/jedi/inference/names.py", line 620, in __getattr__
    return getattr(self._wrapped_name, name)
  File "/home/username/.local/lib/python3.9/site-packages/jedi/inference/value/klass.py", line 80, in api_type
    if definition.type == 'funcdef':
AttributeError: 'NoneType' object has no attribute 'type'
exception calling callback for <Future at 0x7f62f18640a0 state=finished raised RuntimeError>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/username/.local/lib/python3.9/site-packages/prompt_toolkit/eventloop/async_generator.py", line 52, in runner
    loop.call_soon_threadsafe(q.put_nowait, _done)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

```

**Comment by dstei** [comment]
I have a very similar problem with the same "AttributeError: 'NoneType' object has no attribute 'type'". For complete error message see below. This started occurring after updating several packages after a switch to conda-forge, most notably python 3.9.0 -> 3.9.4. (The other changed packages you can find below.) Atm I almost exlusively use pandas, where it often happens on join operations, maybe connected to NaN values. 

error message:
```
Traceback (most recent call last):                                                                                                                                                   File "c:\users\username\miniconda3\envs\py39ml\lib\runpy.py", line 197, in _run_module_as_main                                                                                         return _run_code(code, main_globals, None,                                                                                                                                       File "c:\users\username\miniconda3\envs\py39ml\lib\runpy.py", line 87, in _run_code                                                                                                    exec(code, run_globals)                                                                                                                                                          File "C:\Users\username\Miniconda3\envs\py39ML\Scripts\ptpython.exe\__main__.py", line 7, in <module>                                                                                File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\ptpython\entry_points\run_ptpython.py", line 205, in run                                                         embed(                                                                                                                                                                           File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\ptpython\repl.py", line 692, in embed                                                                            repl.run()                                                                                                                                                                       File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\ptpython\repl.py", line 107, in run                                                                              text = self.read()                                                                                                                                                               File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\ptpython\python_input.py", line 1027, in read                                                                    result = self.app.run(pre_run=pre_run, in_thread=True)                                                                                                                           File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\application\application.py", line 870, in run                                                     raise exception                                                                                                                                                                  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\application\application.py", line 851, in run_in_thread                                           result = self.run(                                                                                                                                                               File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\application\application.py", line 887, in run                                                     return loop.run_until_complete(                                                                                                                                                  File "c:\users\username\miniconda3\envs\py39ml\lib\asyncio\base_events.py", line 642, in run_until_complete                                                                            return future.result()                                                                                                                                                           File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\application\application.py", line 816, in run_async                                               return await _run_async2()                                                                                                                                                       File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\application\application.py", line 798, in _run_async2                                             await self.cancel_and_wait_for_background_tasks()                                                                                                                                File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\application\application.py", line 945, in cancel_and_wait_for_background_tasks                    await task                                                                                                                                                                       File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\buffer.py", line 1909, in new_coroutine                                                           await coroutine(*a, **kw)                                                                                                                                                        File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\buffer.py", line 1738, in async_completer                                                         async for completion in self.completer.get_completions_async(                                                                                                                    File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\completion\base.py", line 227, in get_completions_async                                           async for completion in generator_to_async_generator(                                                                                                                            File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\eventloop\async_generator.py", line 74, in generator_to_async_generator                           await runner_f                                                                                                                                                                   File "c:\users\username\miniconda3\envs\py39ml\lib\concurrent\futures\thread.py", line 52, in run                                                                                      result = self.fn(*self.args, **self.kwargs)                                                                                                                                      File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\eventloop\async_generator.py", line 43, in runner                                                 for item in get_iterable():                                                                                                                                                      File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\completion\base.py", line 228, in <lambda>                                                        lambda: self.completer.get_completions(document, complete_event)                                                                                                                 File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\ptpython\completer.py", line 601, in get_completions                                                             completions = list(self.completer.get_completions(document, complete_event))                                                                                                     File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\completion\deduplicate.py", line 28, in get_completions                                           for completion in self.completer.get_completions(document, complete_event):                                                                                                      File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\prompt_toolkit\completion\base.py", line 329, in get_completions                                                 for c in completer.get_completions(document, complete_event):                                                                                                                    File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\ptpython\completer.py", line 193, in get_completions                                                             yield from self._jedi_completer.get_completions(                                                                                                                                 File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\ptpython\completer.py", line 260, in get_completions                                                             jedi_completions = sorted(                                                                                                                                                       File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\ptpython\completer.py", line 264, in <lambda>                                                                    jc.type != "param",                                                                                                                                                              File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\jedi\api\classes.py", line 719, in type                                                                          return super().type                                                                                                                                                              File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\jedi\api\classes.py", line 189, in type                                                                          return self._name.api_type                                                                                                                                                       File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\jedi\inference\names.py", line 620, in __getattr__                                                               return getattr(self._wrapped_name, name)                                                                                                                                         File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\jedi\inference\value\klass.py", line 80, in api_type                                                             if definition.type == 'funcdef':                                                                                                                                               AttributeError: 'NoneType' object has no attribute 'type'
```

Changed packages:
```
2021-05-19 10:28:49  (rev 10)
     brotlipy  {0.7.0 (defaults/win-64) -> 0.7.0 (conda-forge/win-64)}
     ca-certificates  {2021.1.19 (defaults/win-64) -> 2020.12.5 (conda-forge/win-64)}
     certifi  {2020.12.5 (defaults/win-64) -> 2020.12.5 (conda-forge/win-64)}
     chardet  {4.0.0 (defaults/win-64) -> 4.0.0 (conda-forge/win-64)}
     cryptography  {3.4.6 (defaults/win-64) -> 3.4.7 (conda-forge/win-64)}
     idna  {2.10 (defaults/noarch) -> 2.10 (conda-forge/noarch)}
     m2w64-gcc-libgfortran  {5.3.0 (defaults/win-64) -> 5.3.0 (conda-forge/win-64)}
     m2w64-gcc-libs  {5.3.0 (defaults/win-64) -> 5.3.0 (conda-forge/win-64)}
     m2w64-gcc-libs-core  {5.3.0 (defaults/win-64) -> 5.3.0 (conda-forge/win-64)}
     m2w64-gmp  {6.1.0 (defaults/win-64) -> 6.1.0 (conda-forge/win-64)}
     m2w64-libwinpthread-git  {5.0.0.4634.697f757 (defaults/win-64) -> 5.0.0.4634.697f757 (conda-forge/win-64)}
     msys2-conda-epoch  {20160418 (defaults/win-64) -> 20160418 (conda-forge/win-64)}
     openssl  {1.1.1j (defaults/win-64) -> 1.1.1k (conda-forge/win-64)}
     pybind11  {2.5.0 (defaults/win-64) -> 2.6.2 (conda-forge/win-64)}
     pyopenssl  {20.0.1 (defaults/noarch) -> 20.0.1 (conda-forge/noarch)}
     pysocks  {1.7.1 (defaults/win-64) -> 1.7.1 (conda-forge/win-64)}
     python  {3.9.0 (defaults/win-64) -> 3.9.4 (conda-forge/win-64)}
     requests  {2.25.1 (defaults/noarch) -> 2.25.1 (conda-forge/noarch)}
     setuptools  {50.3.1 (defaults/win-64) -> 49.6.0 (conda-forge/win-64)}
     sqlite  {3.33.0 (defaults/win-64) -> 3.35.5 (conda-forge/win-64)}
     tzdata  {2020d (defaults/noarch) -> 2021a (conda-forge/noarch)}
     urllib3  {1.26.4 (defaults/noarch) -> 1.26.4 (conda-forge/noarch)}
     vc  {14.1 (defaults/win-64) -> 14.2 (conda-forge/win-64)}
     vs2015_runtime  {14.16.27012 (defaults/win-64) -> 14.28.29325 (conda-forge/win-64)}
     wheel  {0.35.1 (defaults/noarch) -> 0.36.2 (conda-forge/noarch)}
     win_inet_pton  {1.1.0 (defaults/win-64) -> 1.1.0 (conda-forge/win-64)}
     wincertstore  {0.2 (defaults/win-64) -> 0.2 (conda-forge/win-64)}
     zlib  {1.2.11 (defaults/win-64) -> 1.2.11 (conda-forge/win-64)}
    +odfpy-1.4.1 (conda-forge/noarch)
    +pybind11-global-2.6.2 (conda-forge/win-64)
```

**Comment by dstei** [comment]
Ok, so I rolled back to 3.9.0, and the error still occurs (first time on a `join`, second time on a `to_csv`). Unfortunately, it is not reproducible. Both times I repeated the steps to get to the same join/export operation, both times it worked on the second try. (While trying to reproduce, I left out steps not necessary to get to the result, so no _exact_ reproduction.)

**Comment by ECon87** [comment]
The problem is still there for me too. And yes it's occurs randomly (not reproducible). True shame, because I really really liked the concept. I guess I will be moving back to ipython.

**Comment by dstei** [comment]
Some weeks later and updating to the latest release, I gave it another try – and the situation has improved for me. The very same error as quoted above (June 1) still occurs kind of randomly, but now does not force ptpython to quit. Instead, just retrying the command leading to the error works. So not unusable anymore :)
