### ISSUE TITLE
`ValueError: I/O operation on closed file` when I exit REPL

### ISSUE THREAD

**Issue by eggplants** [prompt-toolkit/ptpython#463]
```bash
$ python -V
Python 3.8.8
$ ptpython --version
3.0.18
$ ptpython
>>> exit()
```
```python
Traceback (most recent call last):
  File "/home/eggplants/.pyenv/versions/3.8.8/bin/ptpython", line 8, in <module>
    sys.exit(run())
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/ptpython/entry_points/run_ptpython.py", line 207, in run
    embed(
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/ptpython/repl.py", line 720, in embed
    repl.run()
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/ptpython/repl.py", line 135, in run
    text = self.read()
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/ptpython/python_input.py", line 1045, in read
    result = self.app.run(pre_run=pre_run, in_thread=True)
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 874, in run
    raise exception
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 855, in run_in_thread
    result = self.run(
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 792, in _run_async2
    result = await _run_async()
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 721, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "/home/eggplants/.pyenv/versions/3.8.8/lib/python3.8/site-packages/prompt_toolkit/input/vt100.py", line 129, in raw_mode
    return raw_mode(self.stdin.fileno())
ValueError: I/O operation on closed file
```

**Comment by johnfaucette** [comment]
I can confirm exact same error on `Python 3.9.5`.

**Comment by eggplants** [comment]
@johnfaucette Year, I'm using `zsh` and Ubuntu 21.04.

**Comment by eggplants** [comment]
@johnfaucette Yeah, I'm using `zsh` and Ubuntu 21.04.

**Comment by RyannDaGreat** [comment]
Same thing happens when you call quit()

**Comment by JackofSpades707** [comment]
This doesn't have anything to do with using zsh. It happens on sh, bash, and xonsh as well

**Comment by JackofSpades707** [comment]
Looks like we should reference this in prompt toolkit

**Comment by JackofSpades707** [comment]
Relevant Issue: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1456

**Comment by jonathanslenders** [comment]
I'm not sure how this suddenly turned up. I can't reproduce it when running `exit()`, but I can when running `sys.stdin.close()`.

This pull request should fix it: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1457
Would any of you be able to test it? Then I'll merge it.

**Comment by eggplants** [comment]
```bash
$ pip uninstall prompt-toolkit ptpython -y
$ pip install git+https://github.com/prompt-toolkit/python-prompt-toolkit@fix-valueerror-io-operation-on-closed-file
```

**Comment by jonathanslenders** [comment]
I pushed a new release to PyPI, so you should also be able to get it from there. Thanks for testing!
