### ISSUE TITLE
Infitine exception loop in asyncio coroutine mode on exit() or quit()

### ISSUE THREAD

**Issue by brownan** [prompt-toolkit/ptpython#541]
If you run the async example from here: https://github.com/prompt-toolkit/ptpython/blob/master/examples/asyncio-python-embed.py

and execute a `exit()` or `quit()` statement, the prompt goes into an infinite loop of errors that look like this:
```
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 955, in run
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-178'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/venv/lib/python3.9/site-packages/ptpython/repl.py", line 202, in run_async
    text = await loop.run_in_executor(None, self.read)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/ptpython/python_input.py", line 1095, in read
    result = self.app.run(pre_run=pre_run, in_thread=True)
  File "/tmp/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 943, in run
    raise exception
  File "/tmp/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 929, in run_in_thread
    result = self.run(
  File "/tmp/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 958, in run
    return asyncio.run(coro)
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 875, in run_async
    return await _run_async(f)
  File "/tmp/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 728, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "/tmp/venv/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 134, in raw_mode
    return raw_mode(self.stdin.fileno())

```

I have to Ctrl-Z to pause the process or kill it from another window, since Ctrl-C is not effective at this point.

The thread ID in the exception message increases, so I gather it's continuously spawning threads which each crash since stdin has been closed by `exit()`

This is on Ubuntu linux 20.04 with Python 3.9

**Comment by brownan** [comment]
Did some digging. In the repl.py function `run_and_show_expression_async()` a SystemExit is handled by returning.

https://github.com/prompt-toolkit/ptpython/blob/91d2c3589310452a0f79f2fa1a4a6847fc095481/ptpython/repl.py#L156-L176

This swallows the exception and causes the calling code in `run_async()` to proceed to its next iteration. Calling in to read a new line of input gets the error about I/O operation on closed file.

The sync version, however, re-raises a SystemExit:

https://github.com/prompt-toolkit/ptpython/blob/91d2c3589310452a0f79f2fa1a4a6847fc095481/ptpython/repl.py#L96-L115

Is there any reason for the async version to not also do the same?

These two commits are related:
https://github.com/prompt-toolkit/ptpython/commit/742c6d7c77fe03a42554304131083213b6103d63
https://github.com/prompt-toolkit/ptpython/commit/78c5a0df8d37c24d97c933a7f820afdd179bab28
